/**
 * Generated by openapi-typescript. Do not edit manually.
 * Run `npm run codegen` to regenerate from the live API.
 *
 * Source: {API_URL}/openapi.json
 */

export interface paths {}
export interface components {}
export interface operations {}
