/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/{provider}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Login */
        get: operations["oauth_login_api_auth__provider__login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Callback */
        get: operations["oauth_callback_api_auth__provider__callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_api_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recipes */
        get: operations["list_recipes_api_recipes_get"];
        put?: never;
        /** Create Recipe */
        post: operations["create_recipe_api_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Recipe */
        delete: operations["delete_recipe_api_recipes__recipe_id__delete"];
        options?: never;
        head?: never;
        /** Update Recipe */
        patch: operations["update_recipe_api_recipes__recipe_id__patch"];
        trace?: never;
    };
    "/api/recipes/{recipe_id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Favorite */
        post: operations["add_favorite_api_recipes__recipe_id__favorite_post"];
        /** Remove Favorite */
        delete: operations["remove_favorite_api_recipes__recipe_id__favorite_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Recipe */
        post: operations["restore_recipe_api_recipes__recipe_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}/permanent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Permanently Delete Recipe */
        delete: operations["permanently_delete_recipe_api_recipes__recipe_id__permanent_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mine */
        get: operations["list_mine_api_recipes_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/trashed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trashed */
        get: operations["list_trashed_api_recipes_trashed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_api_recipes__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Favorites */
        get: operations["list_favorites_api_users_me_favorites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Upload */
        post: operations["sign_upload_api_uploads_sign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CategoryOut */
        CategoryOut: {
            /** Id */
            id: string;
            /** Items */
            items: components["schemas"]["app__routers__categories__CategoryItemOut"][];
        };
        /** FavoriteOut */
        FavoriteOut: {
            /** Is Favorited */
            is_favorited: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngredientIn */
        IngredientIn: {
            /** Position */
            position: number;
            /** Quantity */
            quantity?: number | string | null;
            /** Unit */
            unit?: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
        };
        /** IngredientOut */
        IngredientOut: {
            /** Id */
            id: string;
            /** Position */
            position: number;
            /** Quantity */
            quantity: string | null;
            /** Unit */
            unit: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
        };
        /** OwnerPublic */
        OwnerPublic: {
            /** Name */
            name: string;
            /** Avatar Url */
            avatar_url: string | null;
        };
        /** PaginatedRecipes */
        PaginatedRecipes: {
            /** Items */
            items: components["schemas"]["RecipeListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** RecipeIn */
        RecipeIn: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Image Public Id */
            image_public_id?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Servings */
            servings?: number | null;
            /** Prep Time Minutes */
            prep_time_minutes?: number | null;
            /** Cook Time Minutes */
            cook_time_minutes?: number | null;
            /**
             * Steps
             * @default []
             */
            steps: components["schemas"]["RecipeStep"][];
            /**
             * Is Public
             * @default true
             */
            is_public: boolean;
            /**
             * Ingredients
             * @default []
             */
            ingredients: components["schemas"]["IngredientIn"][];
            /**
             * Category Item Ids
             * @default []
             */
            category_item_ids: string[];
            /**
             * Tag Ids
             * @default []
             */
            tag_ids: string[];
        };
        /** RecipeListItem */
        RecipeListItem: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Image Url */
            image_url: string | null;
            /** Is Public */
            is_public: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            owner: components["schemas"]["OwnerPublic"];
            /** Category Item Ids */
            category_item_ids: string[];
            /** Tag Ids */
            tag_ids: string[];
            /** Is Favorited */
            is_favorited?: boolean | null;
        };
        /** RecipeOut */
        RecipeOut: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Image Url */
            image_url: string | null;
            /** Image Public Id */
            image_public_id: string | null;
            /** Source Url */
            source_url: string | null;
            /** Servings */
            servings: number | null;
            /** Prep Time Minutes */
            prep_time_minutes: number | null;
            /** Cook Time Minutes */
            cook_time_minutes: number | null;
            /** Steps */
            steps: components["schemas"]["RecipeStep"][];
            /** Is Public */
            is_public: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            owner: components["schemas"]["OwnerPublic"];
            /** Ingredients */
            ingredients: components["schemas"]["IngredientOut"][];
            /** Category Items */
            category_items: components["schemas"]["app__routers__recipes__CategoryItemOut"][];
            /** Tags */
            tags: components["schemas"]["TagOut"][];
            /** Is Favorited */
            is_favorited?: boolean | null;
        };
        /** RecipePatch */
        RecipePatch: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Image Public Id */
            image_public_id?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Servings */
            servings?: number | null;
            /** Prep Time Minutes */
            prep_time_minutes?: number | null;
            /** Cook Time Minutes */
            cook_time_minutes?: number | null;
            /** Steps */
            steps?: components["schemas"]["RecipeStep"][] | null;
            /** Is Public */
            is_public?: boolean | null;
            /** Ingredients */
            ingredients?: components["schemas"]["IngredientIn"][] | null;
            /** Category Item Ids */
            category_item_ids?: string[] | null;
            /** Tag Ids */
            tag_ids?: string[] | null;
        };
        /** RecipeStep */
        RecipeStep: {
            /** Position */
            position: number;
            /** Text */
            text: string;
        };
        /** SignedUploadParams */
        SignedUploadParams: {
            /** Cloud Name */
            cloud_name: string;
            /** Api Key */
            api_key: string;
            /** Timestamp */
            timestamp: number;
            /** Signature */
            signature: string;
            /** Folder */
            folder: string;
        };
        /** TagIn */
        TagIn: {
            /** Name */
            name: string;
        };
        /** TagOut */
        TagOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** TrashedRecipeItem */
        TrashedRecipeItem: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Image Url */
            image_url: string | null;
            /**
             * Deleted At
             * Format: date-time
             */
            deleted_at: string;
        };
        /** UserPublic */
        UserPublic: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Avatar Url */
            avatar_url: string | null;
            /** Provider */
            provider: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** CategoryItemOut */
        app__routers__categories__CategoryItemOut: {
            /** Id */
            id: string;
        };
        /** CategoryItemOut */
        app__routers__recipes__CategoryItemOut: {
            /** Id */
            id: string;
            /** Category Id */
            category_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    oauth_login_api_auth__provider__login_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_callback_api_auth__provider__callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
        };
    };
    create_tag_api_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recipes_api_recipes_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                category_items?: string[];
                tags?: string[];
            };
            header?: never;
            path?: never;
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecipes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recipe_api_recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipe_api_recipes__recipe_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recipe_api_recipes__recipe_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_favorite_api_recipes__recipe_id__favorite_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_favorite_api_recipes__recipe_id__favorite_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_recipe_api_recipes__recipe_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    permanently_delete_recipe_api_recipes__recipe_id__permanent_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mine_api_recipes_mine_get: {
        parameters: {
            query?: {
                category_items?: string[];
                tags?: string[];
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trashed_api_recipes_trashed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashedRecipeItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_api_recipes__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_favorites_api_users_me_favorites_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                category_items?: string[];
                tags?: string[];
            };
            header?: never;
            path?: never;
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecipes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_upload_api_uploads_sign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                auth_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedUploadParams"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
